void create_account();
void write_prompt(string question);
void prompt_username();
void prompt_email();
void prompt_new_username();
void prompt_existing_password();
void prompt_new_password();
void prompt_player();
void prompt_player_choice(string *players);
void prompt_player_selection();
void start_session(string player_name);
void clear_pending();
void write_password_advice();
string normalize_value(string value);
string format_display_name(string value);
int is_valid_email(string email);
int is_valid_username(string name);
int is_valid_password(string password);
int contains_profanity(string value);
string make_salt();
